#:schema node_modules/wrangler/config-schema.json
name = "farma-be"
main = "src/index.ts"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "farma-db"
database_id = "8fe387c0-2a33-4a7f-bbc0-97bcf3972228"
migrations_dir = "drizzle/migrations"
